# Generated by Django 2.0.2 on 2018-04-11 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='userDownVotesComments',
            field=models.ManyToManyField(blank=True, related_name='comment_user_down', to='app.Profile'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='userUpVotesComments',
            field=models.ManyToManyField(blank=True, related_name='comment_user_up', to='app.Profile'),
        ),
        migrations.AlterField(
            model_name='post',
            name='userDownVotesPost',
            field=models.ManyToManyField(blank=True, related_name='post_user_down', to='app.Profile'),
        ),
        migrations.AlterField(
            model_name='post',
            name='userUpVotesPost',
            field=models.ManyToManyField(blank=True, related_name='post_user_up', to='app.Profile'),
        ),
    ]
