# Generated by Django 2.0.2 on 2018-03-23 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='user_details',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
