# Generated by Django 2.0.2 on 2018-04-06 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='user_picture',
            field=models.ImageField(blank=True, upload_to='user_data/pictures/'),
        ),
    ]
