# Generated by Django 2.0.2 on 2018-04-12 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20180411_1449'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='userHidden',
            field=models.ManyToManyField(blank=True, related_name='user_post_hidden', to='app.Profile'),
        ),
        migrations.AddField(
            model_name='post',
            name='userSaved',
            field=models.ManyToManyField(blank=True, related_name='user_post_saved', to='app.Profile'),
        ),
    ]
