# Generated by Django 2.0.2 on 2018-04-09 10:59

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_profile_user_picture'),
    ]

    operations = [
        migrations.AddField(
            model_name='topic',
            name='creation_date',
            field=models.DateField(default=datetime.datetime.now),
        ),
        migrations.AlterField(
            model_name='profile',
            name='user_picture',
            field=models.ImageField(blank=True, default='user_data/pictures/no-img.jpg', upload_to='user_data/pictures/'),
        ),
    ]
