# Generated by Django 2.0.2 on 2018-04-09 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20180409_1059'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='user_picture',
            field=models.ImageField(blank=True, default='app/static/images/profile_pic.jpg', upload_to='user_data/pictures/'),
        ),
    ]
