# Generated by Django 2.0.2 on 2018-04-15 23:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20180414_1438'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='profile_comments_permission',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='profile',
            name='profile_friends_permission',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='profile',
            name='profile_posts_permission',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='profile',
            name='profile_topics_permission',
            field=models.BooleanField(default=False),
        ),
    ]
