# Generated by Django 2.0.2 on 2018-04-15 23:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_auto_20180415_2328'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profile_comments_permission',
            field=models.CharField(choices=[('N', 'No One'), ('F', 'Friends'), ('E', 'Everybody')], default='F', max_length=1),
        ),
        migrations.AlterField(
            model_name='profile',
            name='profile_friends_permission',
            field=models.CharField(choices=[('N', 'No One'), ('F', 'Friends'), ('E', 'Everybody')], default='F', max_length=1),
        ),
        migrations.AlterField(
            model_name='profile',
            name='profile_posts_permission',
            field=models.CharField(choices=[('N', 'No One'), ('F', 'Friends'), ('E', 'Everybody')], default='F', max_length=1),
        ),
        migrations.AlterField(
            model_name='profile',
            name='profile_topics_permission',
            field=models.CharField(choices=[('N', 'No One'), ('F', 'Friends'), ('E', 'Everybody')], default='F', max_length=1),
        ),
    ]
