# Generated by Django 2.0.2 on 2018-04-09 14:16

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_auto_20180409_1415'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='registration_date',
            field=models.DateField(default=datetime.datetime.now),
        ),
    ]
