# Generated by Django 2.0.2 on 2018-04-16 01:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_auto_20180416_0047'),
    ]

    operations = [
        migrations.AlterField(
            model_name='friend',
            name='users',
            field=models.ManyToManyField(blank=True, to='app.Profile'),
        ),
    ]
