# Generated by Django 2.0.2 on 2018-04-16 01:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_auto_20180416_0135'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='profile_info_permission',
            field=models.CharField(choices=[('N', 'No One'), ('F', 'Friends'), ('E', 'Everybody')], default='F', max_length=1),
        ),
    ]
