# Generated by Django 2.0.2 on 2018-04-16 01:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_profile_profile_info_permission'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='subscriptions',
            field=models.ManyToManyField(blank=True, to='app.Topic'),
        ),
    ]
